import mods.ResearchTable;
//mods.recipestages.Recipes.setRecipeStage("one", <minecraft:stone_hoe>);

//ResearchTable.builder("")
//.setTitle("")
//.setIcons()
//.setDescription("")
//.addCondition()
//.addCondition()
//.setRewardStages("")
//.build();
ResearchTable.builder("iron")
  .setTitle("Tools+")
  .setIcons(<minecraft:iron_ingot>)
  .setDescription("Access to iron")
  .addCondition(<minecraft:cobblestone> * 250)
  .addCondition(<minecraft:log> * 100)
  .setRewardStages("iron")
  .build();
ResearchTable.builder("basicauto")
  .setTitle("Early Logistics")
  .setIcons(<logisticalautomation:conveyor_stone>)
  .setDescription("Basic Conveyors and tools")
  .addCondition(<immersiveengineering:metal:39> * 250)
  .addCondition(<projectred-core:resource_item:400> * 300)
  .setRewardStages("basicauto")
  .build();
ResearchTable.builder("conveyors1")
.setTitle("Conveyor Upgrade 1")
.setIcons(<logisticalautomation:conveyor_normal>)
.setDescription("An upgrade in speed to the Stone Conveyor")
.addCondition(<logisticalautomation:conveyor_stone> * 25)
.addCondition(<logisticalautomation:iron_motor_set> * 50)
.setRewardStages("conveyors1")
.build();
ResearchTable.builder("conveyors2")
.setTitle("Conveyor Upgrade 2")
.setIcons(<logisticalautomation:conveyor_fast>)
.setDescription("An upgrade in speed to the Normal conveyor")
.addCondition(<logisticalautomation:conveyor_normal> * 100)
.addCondition(<logisticalautomation:gold_motor_set> * 200)
.setRewardStages("conveyors2")
.build();
ResearchTable.builder("conveyors3")
.setTitle("Conveyor Upgrade 3")
.setIcons(<logisticalautomation:conveyor_express>)
.setDescription("An upgrade in speed to the Fast conveyor")
.addCondition(<logisticalautomation:conveyor_fast> * 250)
.addCondition(<immersiveengineering:metal:39> * 1500)
.setRewardStages("conveyors3")
.build();
ResearchTable.builder("tt2")
.setTitle("Tech Tier 2")
.setIcons(<logisticalautomation:gold_motor_set>)
.setDescription("More complex tools for more complex automation")
.addCondition(<logisticalautomation:iron_motor_set> * 150)
.addCondition(<moreplates:gold_stick> * 150)
.setRewardStages("cmplx1")
.build();
ResearchTable.builder("conveyorutils")
.setTitle("Conveyors+")
.setIcons(<logisticalautomation:splitter>)
.setDescription("Tools to make life easier")
.addCondition(<logisticalautomation:gold_motor_set> * 100)
.addCondition(<immersiveengineering:metal:39> * 600)
.setRewardStages("conveyorutils")
.build();
ResearchTable.builder("catwalks")
.setTitle("Catwalks")
.setIcons(<logisticalautomation:catwalk>)
.setDescription("To help you view your factory from above")
.addCondition(<immersiveengineering:metal:39> * 250)
.addCondition(<immersiveengineering:material:1> * 250)
.addCondition(<minecraft:iron_bars> * 500)
.setRewardStages("catwalks") 
.build();